import { FC, ReactNode } from 'react'
import type { Metadata } from 'next'
import { JetBrains_Mono } from 'next/font/google'
import Header from '@/components/Header'
import PageTransition from '@/components/PageTransition'
import StairsTransition from '@/components/StairsTransition'
import './globals.css'

const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

const RootLayout: FC<Readonly<RootLayoutProps>> = ({ children }) => {
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable}>
        <Header />
        <StairsTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  )
}

export default RootLayout
